-- Tabel untuk menyimpan data gadai HP dan Laptop dengan sistem verifikasi
CREATE TABLE IF NOT EXISTS `data_gadai` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nama_nasabah` varchar(255) NOT NULL,
  `no_ktp` varchar(16) NOT NULL,
  `no_hp` varchar(20) NOT NULL,
  `alamat` text NOT NULL,
  `jenis_barang` enum('HP','Laptop') NOT NULL,
  `merk` varchar(100) NOT NULL,
  `tipe` varchar(100) NOT NULL,
  `kondisi` enum('Sangat Baik','Baik','Cukup') NOT NULL,
  `imei_serial` varchar(100) NOT NULL,
  `kelengkapan_hp` text DEFAULT NULL,
  `harga_pasar` decimal(15,2) NOT NULL,
  `jumlah_pinjaman` decimal(15,2) NOT NULL COMMENT 'Nominal yang diajukan user',
  `jumlah_disetujui` decimal(15,2) DEFAULT NULL COMMENT 'Nominal yang disetujui admin',
  `bunga` decimal(5,2) NOT NULL DEFAULT 30.00,
  `lama_gadai` int(11) NOT NULL,
  `tanggal_gadai` date NOT NULL,
  `tanggal_jatuh_tempo` date NOT NULL,
  `foto_barang` varchar(255) DEFAULT NULL,
  `foto_ktp` varchar(255) DEFAULT NULL,
  `status` enum('Pending','Disetujui','Ditolak','Ditebus','Dijual','Diperpanjang','Gagal Tebus') NOT NULL DEFAULT 'Pending',
  `aksi_jatuh_tempo` enum('Perpanjangan','Pelunasan') DEFAULT NULL,
  `aksi_jatuh_tempo_at` datetime DEFAULT NULL,
  `perpanjangan_ke` int(11) NOT NULL DEFAULT 0,
  `perpanjangan_terakhir_at` datetime DEFAULT NULL,
  `gagal_tebus_at` datetime DEFAULT NULL,
  `denda_terakumulasi` decimal(15,2) NOT NULL DEFAULT 0,
  `total_tebus` decimal(15,2) NOT NULL DEFAULT 0,
  `reminder_3hari_at` datetime DEFAULT NULL,
  `reminder_3hari_due_date` date DEFAULT NULL,
  `reminder_telat_at` datetime DEFAULT NULL,
  `reminder_telat_due_date` date DEFAULT NULL,
  `reminder_telat_last_day` int(11) DEFAULT NULL,
  `verified_at` timestamp NULL DEFAULT NULL,
  `verified_by` varchar(100) DEFAULT NULL,
  `reject_reason` text DEFAULT NULL COMMENT 'Alasan penolakan',
  `keterangan_admin` text DEFAULT NULL COMMENT 'Catatan admin saat menyetujui',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `no_ktp` (`no_ktp`),
  KEY `status` (`status`),
  KEY `tanggal_jatuh_tempo` (`tanggal_jatuh_tempo`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
